version: '2'
services:
  db:
    image: postgres:9.6-alpine

  redis:
    image: redis:3-alpine

  fakes3:
    image: instructure/fake-s3
    ports:
      - "4569:4569"
    environment:
      VIRTUAL_HOST: .fakes3.docker
      VIRTUAL_PORT: 4569

  web:
    build:
      context: .
      args:
        dev_build: 'true'
    links:
      - db
      - redis
      - fakes3
    environment: &ENV
      RAILS_ENV: development
      ROLLCALL_ROLE: web
      #VIRTUAL_HOST: rollcall.docker
      DATABASE_URL: postgres://postgres@db:5432/rollcall_dev
      REDIS_URL: redis://redis:6379
      # SENTRY_DSN: 'https://foo:bar@sentry.insops.net/35'
      SECRET_KEY_BASE: 'GSOC6DGMsvlLtDkaAagn7HBtxO4FJZECVYVuceZV7LMGMaYTIBXbK5OLa3UC'
      RESQUE_USER: 'admin'
      RESQUE_PASS: 'changeme'
      AWS_ACCESS_KEY_ID: '123'
      AWS_SECRET_ACCESS_KEY: 'secret'
      AWS_REGION: 'us-east-1'
      AWS_S3_ENDPOINT: 'http://fakes3.docker'
      LTI_KEY: '12345'
      LTI_SECRET: 'secret'
      LTI_REQUIRE_CANVAS: 'true'

  work:
    build:
      context: .
      args:
        dev_build: 'true'
    links:
      - db
      - redis
    environment:
      <<: *ENV
      ROLLCALL_ROLE: 'worker'
      QUEUE: "*"
